### ISSUE TITLE
Copyright issue. Removed all copyrights from sources

### ISSUE THREAD

**Issue by 4144** [brAthena/brAthena#14]
Original copyrights in all files must stand unchanged

In original files was copyrights:
```
// Copyright (c) Hercules Dev Team, licensed under GNU GPL.
// See the LICENSE file
// Portions Copyright (c) Athena Dev Teams
```

If you want add own copyrights, it must have similar look to this example:
```
// Copyright (c) Hercules Dev Team, licensed under GNU GPL.
// See the LICENSE file
// Portions Copyright (c) Athena Dev Teams
/****************************************************************************!
*                _           _   _   _                                       *
*               | |__  _ __ / \ | |_| |__   ___ _ __   __ _                  *
*               | '_ \| '__/ _ \| __| '_ \ / _ \ '_ \ / _` |                 *
*               | |_) | | / ___ \ |_| | | |  __/ | | | (_| |                 *
*               |_.__/|_|/_/   \_\__|_| |_|\___|_| |_|\__,_|                 *
*                                                                            *
******************************************************************************
*                          www.brathena.org                                  *
*****************************************************************************/
```

**Comment by AlyPhoenix** [comment]
Hi Andrei, we're working on the headers, but thanks for pointing that.

**Comment by Megasantos** [comment]
@4144 Concordo dos cabeçalhos, inclusive abra um reporte desses no Hercules para dar direitos autorais a fonte do rAthena pois o Hercules foi um fork do rAthena que veio do eAthena.

**Comment by 4144** [comment]
@Megasantos In rAthena sources i not see any rathena copyrights, only eAthena and it stand in hercules too.
In hercules own copyrights present and must stand in all forks like brAthena.

But yes, if you really want, you can add also rAthena copyrights into brAthena.

**Comment by AlyPhoenix** [comment]
Megasantos said Hercules needs rAthena copyrights too, 'cause it's a rAthena's fork.

And actually it doesn't stand unchanged in Hercules, you put Athena in Portions Copyright, so we will put Hercules in it too. It is fair, right huh?

// Copyright (c) brAthena Dev Team, licensed under GNU GPL.
// See the LICENSE file
// Portions Copyright (C) Athena and Hercules Dev Teams

**Comment by Megasantos** [comment]
@4144 I understand that you're not guilty. But hercules should give credits to rAthena. Because many rAthena codes exist in hercules.

I'm just exposing my opinion

**Comment by TidusBR** [comment]
Hercules is a fork of rAthena and does not hold the copyright of the same. We gave fork in Hercules but never removed the credits of the same.

**Comment by 4144** [comment]
rAthana copyrights was not present in rAthena sources.
Copyright is not who did code, but who from devs wrote copyrights.
But if some one add, it must stand.

Actualy changed copyright lines in hercules is not very correct.
In best case better get upstream copyrights and add own before or after. Probably we will fix changed copyrights lines in hercules.

Example from @AlyPhoenix is better than nothing, but still better not change other copyrights and add own.

For my look best example for brAthena will be:
```
// Copyright (c) Athena Dev Teams - Licensed under GNU GPL
// Copyright (c) Hercules Dev Team, licensed under GNU GPL.
// Copyright (c) brAthena Dev Team, licensed under GNU GPL.
// See the LICENSE file
```
here no rAthena copyrights, because they not add it.

**Comment by Megasantos** [comment]
@4144 I would also like to address an issue. My translation of fluxcp was added in FluxCP hercules by JulioCF moderator without my permission, I spoke with gepard and even said he would give credit, the more he disappeared.

I believe it would be fair to give credit to me not? For the JulioCF took my translation and added in hercules.

my Flux: https://github.com/Megasantos/Fluxcp/blob/master/lang/pt_br.php

Flux Herc: https://github.com/HerculesWS/FluxCP/blob/master/lang/pt_br.php

**Comment by TidusBR** [comment]
The Hercules has a lot of our stuff, several translations of brAthena and there is no credit, and we never went there demand anything because it comes from contributions from the communities of developments.

I'm here from when eAthena was founded and you is the first novice that comes with this story, I will contact the Ind.

**Comment by 4144** [comment]
@Megasantos better create issue in hercules fluxcp about this.

@TidusBR credits or copyrights not for all present. And actualy in eAthena forks no authors lists. But copyrights cant be deleted from existing code.

in brAthena removed all copyrights and this look like only brAthena created this code, but this is not true.

@TidusBR in translations what you said was brAthena copyrights, and they was removed?

**Comment by Protimus** [comment]
Please, send a PM to an forum administrator or developr to solve this issues. We face this issue with negative image, since you could have solved this problem directly with us and not publicly.

Yes, we need change a lot headers with the appropriate credits. The actual source code is a fork based in hercules. We don't do anything incorrectly because in the old source code had all the credits until the eAthena.

Now I put in evidence the following: Where are the brAthena credits for stolen projects where developers or users simply took and made a similar code or totally equal to ours.
There are several skills, formulas and systems that have been copied from me, the Megasantos and Shiraz. I'll not waste my time quoting what is the commits that have codes stolen, I've done this 1 year ago.

**Comment by MishimaHaruna** [comment]
I apologize for replying to a closed ticket, but I'd like to make some clarification, since the discussion degenerated to unrelated matters.

The first issue is that all the source files in Hercules contain a header that clearly states who the copyright holders are (the line ```// Copyright (c) Hercules Dev Team, licensed under GNU GPL.```). Regardless of what you do, if you use the file as is, you should keep that line intact. If you use portions of the file, it is fine if you prepend 'Portions', as long as you have consistent edits of your own.

The same line also contains a reference to the license the code is licensed as. Since the GNU GPL license is very picky on this matter, you cannot remote that mention. You can separate it from the copyright line or reword it, but the license (see Point 5 in the LICENSE file for example) clearly states that `The work must carry prominent notices stating that it is released under this License`.

Hercules doesn't contain a header line stating rAthena copyrights, because in most files, there was no such line when we forked the project, but just a line mentioning 'Athena Dev Teams', which we kept.
There are some exceptions, where a rAthena copyright line was added (and we never removed), such as thread.c (for which we currently don't claim Hercules copyrights, since it's pretty much unaltered since rAthena).

Your claims about not giving credit are a completely different matter. Credits and copyrights are different things: the first is courtesy, the second is a must. Even so, at Hercules we always give credit where credit is due (usually in the form of a comment in the commit message). If some of our collaborators did not, I extend my apologies for them.

If you feel that any of your copyrights were infringed or misrepresented, please file an issue in our bugtracker and it'll be fixed (if you do, please give us a link to the original source unless very obvious, so that we can verify the claim).

**Comment by JulioCF** [comment]
@Megasantos Eu não peguei da sua, eu peguei nem lembro de onde, se dai foi sua, nada posso fazer(na verdade, irei la agora editar e por seus créditos, se forem realmente seus). Agora eu pergunto, porque não me procurou para me questionar sobre? Você cobra acerto sem precisar fazer o certo. Entendo.

**Comment by Megasantos** [comment]
@JulioCF Simplesmente alguns erros que existia em minha tradução estavam na do hercules, engraçado né como foram parar lá.
 
Você conversa demais, pela idade do senhor deveria ter vergonha, melhor procurar antes de fazer afirmações que não sabe, nunca removi créditos de ninguém, procure primeiro antes de sair falando o que não deve.

https://github.com/Megasantos/Fluxcp/blob/master/themes/default/footer.php#L22

**Comment by JulioCF** [comment]
Mas é inteligente mesmo em. Sabe a quantos anos foi isso? eu nem falei nada na época por dois motivo, 1- pra mim é uma bela frescura esse negócio de reivindicar créditos em emuladores de ragnarok. 2- como comentei, isso foi LAAAA no começo, que não lembro quem me disse que você traduziu, ai fui ver, estava la sem créditos e uma menção dando a entender que o flux foi feito por você e/ou pelo brA, até comentei com a pessoa(que como disse, nem lembro) quem, mas como sempre faço sobre este assunto, taquei um "foda-se" e segui minha vida, como sempre faço. Você pode até ter, derrepente, esquecido de repor na época, deve ter até sido isso que me fez deixar pra la o assunto, também. E como disse, sobre esse bentita "tradução" de sua parte, eu peguei de um flux qualquer que vi com ela no Git, coloquei no flux que esta no meu Git e quando saiu a versão pro Herc, eu coloquei e aceitaram. É assim tão importante pra você? Porque não foi la arrumar conversa fiada(como agora) na época? E sua mesmo? Fosse la avisar! Eu seria o primeiro a adicionar os devidos créditos e por um pedido de desculpas. E esse papo furado de chamar de "senhor" só pra tentar algum mimimi, não cola. É sua a tradução? Nossa, que ótimo em! Meus parabéns e peço desculpas por só descobri agora, que ela é sua.

**Comment by AlyPhoenix** [comment]
Caras, arrumem um quarto para vocês... Se é algo pessoal, favor tratar em private.

Assunto encerrado, e em breve tudo corrigido.
